/*
 * Copyright 2026 CodeMatters, Lda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

syntax = "proto3";

package spine.testing;

// Testlib module doesn't have a dependency on base, thus the use of Spine options, namely
// (type_url) is omitted.
option java_multiple_files = true;
option java_outer_classname = "PrescriptionProto";
option java_package = "io.spine.testing";

import "google/protobuf/timestamp.proto";

// A prescription of a medication.
message Prescription {

    // The date when the prescription was given to a patient.
    google.protobuf.Timestamp prescribed_on = 1;

    // Names of prescribed drugs.
    repeated string prescribed_drug = 2;
}
